### ISSUE TITLE
Exchanges have no idea of precision

### ISSUE THREAD

**Issue by ydm** [thrasher-corp/gocryptotrader#740] opened 2021-08-06 07:01 UTC
On the client side (i.e. `exchange.IBotExchange.SubmitOrder()`) we fill float64s for price, amount, etc. Proper precision should be handled at exchange level as it is (1) exchange-dependent, (2) imprecise to round a float64 on the client side and expect the string representation to reflect that rounding precisely.

**Comment by thrasher-** [comment] 2024-10-31 00:24
Duplicate of https://github.com/thrasher-corp/gocryptotrader/issues/740, will be tracked there

**Closed by thrasher-** 2024-10-31 00:24 UTC
